# Alternates
# TODO: Better way to prioritize/mark these as accessible
recipe: <
  name: "Fire Ice graphene"
  result: <item: "Graphene" quantity: 2>
  result: <item: "Hydrogen" quantity: 1>
  input: <item: "Fire ice" quantity: 2>
  duration: <seconds: 2>
  type: CHEMICAL
>
recipe: <
  name: "X-ray cracking"
  result: <item: "Hydrogen" quantity: 3>
  result: <item: "Energetic graphite" quantity: 1>
  input: <item: "Refined oil" quantity: 1>
  input: <item: "Hydrogen" quantity: 2>
  duration: <seconds: 4>
  type: REFINED
>
recipe: <
  name: "Spinform nanotube"
  result: <item: "Carbon nanotube" quantity: 2>
  input: <item: "Spinform stalagmite crystal" quantity: 2>
  duration: <seconds: 4>
  type: CHEMICAL
>

# Rare veins
recipe: <
  name: "Organic crystal vein"
  result: <item: "Organic crystal" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Fire ice vein"
  result: <item: "Fire ice" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Spinform stalagmite crystal vein"
  result: <item: "Spinform stalagmite crystal" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Sulfuric ocean pump"
  result: <item: "Sulfuric acid" quantity: 1>
  per_minute: 50
  type: LIQUID_HARVESTED
>

# Raw resources
recipe: <
  name: "Coal vein"
  result: <item: "Coal ore" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Stone vein"
  result: <item: "Stone ore" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Iron vein"
  result: <item: "Iron ore" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Copper vein"
  result: <item: "Copper ore" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Silicon vein"
  result: <item: "Silicon ore" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Titanium vein"
  result: <item: "Titanium ore" quantity: 1>
  per_minute: 30
  type: VEIN_HARVESTED
>
recipe: <
  name: "Water pump"
  result: <item: "Water" quantity: 1>
  per_minute: 50
  type: LIQUID_HARVESTED
>
recipe: <
  name: "Crude oil seep"
  result: <item: "Crude oil" quantity: 1>
  per_second: 1
  type: OIL_HARVESTED
>

# Smelting
recipe: <
  result: <item: "Iron ingot" quantity: 1>
  input: <item: "Iron ore" quantity: 1>
  duration: <seconds: 1>
  type: SMELTED
>
recipe: <
  result: <item: "Copper ingot" quantity: 1>
  input: <item: "Copper ore" quantity: 1>
  duration: <seconds: 1>
  type: SMELTED
>
recipe: <
  result: <item: "High-purity silicon" quantity: 1>
  input: <item: "Silicon ore" quantity: 2>
  duration: <seconds: 2>
  type: SMELTED
>
recipe: <
  result: <item: "Crystal silicon" quantity: 1>
  input: <item: "High-purity silicon" quantity: 1>
  duration: <seconds: 2>
  type: SMELTED
>
recipe: <
  result: <item: "Titanium ingot" quantity: 1>
  input: <item: "Titanium ore" quantity: 2>
  duration: <seconds: 2>
  type: SMELTED
>
recipe: <
  result: <item: "Energetic graphite" quantity: 1>
  input: <item: "Coal ore" quantity: 2>
  duration: <seconds: 2>
  type: SMELTED
>
recipe: <
  result: <item: "Diamond" quantity: 1>
  input: <item: "Energetic graphite" quantity: 1>
  duration: <seconds: 2>
  type: SMELTED
>
recipe: <
  result: <item: "Magnet" quantity: 1>
  input: <item: "Iron ore" quantity: 1>
  duration: <seconds: 1 millis: 500>
  type: SMELTED
>
recipe: <
  result: <item: "Glass" quantity: 1>
  input: <item: "Stone ore" quantity: 2>
  duration: <seconds: 2>
  type: SMELTED
>
recipe: <
  result: <item: "Steel" quantity: 1>
  input: <item: "Iron ingot" quantity: 3>
  duration: <seconds: 3>
  type: SMELTED
>
recipe: <
  result: <item: "Titanium alloy" quantity: 4>
  input: <item: "Titanium ingot" quantity: 4>
  input: <item: "Steel" quantity: 4>
  input: <item: "Sulfuric acid" quantity: 6>
  duration: <seconds: 12>
  type: SMELTED
>

# Green science
recipe: <
  result: <item: "Gravity matrix" quantity: 2>
  input: <item: "Graviton lens" quantity: 1>
  input: <item: "Quantum chip" quantity: 1>
  duration: <seconds: 24>
  type: RESEARCHED
>
recipe: <
  result: <item: "Quantum chip" quantity: 1>
  input: <item: "Processor" quantity: 2>
  input: <item: "Plane filter" quantity: 2>
  duration: <seconds: 6>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Plane filter" quantity: 1>
  input: <item: "Casimir crystal" quantity: 1>
  input: <item: "Titanium glass" quantity: 2>
  duration: <seconds: 12>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Casimir crystal" quantity: 1>
  input: <item: "Titanium crystal" quantity: 1>
  input: <item: "Graphene" quantity: 2>
  input: <item: "Hydrogen" quantity: 12>
  duration: <seconds: 4>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Titanium crystal" quantity: 1>
  input: <item: "Organic crystal" quantity: 1>
  input: <item: "Titanium ingot" quantity: 3>
  duration: <seconds: 4>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Organic crystal" quantity: 1>
  input: <item: "Plastic" quantity: 2>
  input: <item: "Refined oil" quantity: 1>
  input: <item: "Water" quantity: 1>
  duration: <seconds: 6>
  type: CHEMICAL
>
recipe: <
  result: <item: "Titanium glass" quantity: 2>
  input: <item: "Glass" quantity: 2>
  input: <item: "Titanium ingot" quantity: 2>
  input: <item: "Water" quantity: 2>
  duration: <seconds: 5>
  type: ASSEMBLED
>

# Purple science
recipe: <
  result: <item: "Information matrix" quantity: 1>
  input: <item: "Processor" quantity: 2>
  input: <item: "Particle broadband" quantity: 1>
  duration: <seconds: 10>
  type: RESEARCHED
>
recipe: <
  result: <item: "Particle broadband" quantity: 1>
  input: <item: "Carbon nanotube" quantity: 2>
  input: <item: "Crystal silicon" quantity: 2>
  input: <item: "Plastic" quantity: 1>
  duration: <seconds: 8>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Carbon nanotube" quantity: 2>
  input: <item: "Graphene" quantity: 3>
  input: <item: "Titanium ingot" quantity: 1>
  duration: <seconds: 4>
  type: CHEMICAL
>
recipe: <
  result: <item: "Graphene" quantity: 2>
  input: <item: "Energetic graphite" quantity: 3>
  input: <item: "Sulfuric acid" quantity: 1>
  duration: <seconds: 3>
  type: CHEMICAL
>
recipe: <
  result: <item: "Sulfuric acid" quantity: 4>
  input: <item: "Refined oil" quantity: 6>
  input: <item: "Stone ore" quantity: 8>
  input: <item: "Water" quantity: 6>
  duration: <seconds: 6>
  type: CHEMICAL
>
recipe: <
  name: "Plasma refining"
  result: <item: "Refined oil" quantity: 2>
  result: <item: "Hydrogen" quantity: 1>
  input: <item: "Crude oil" quantity: 2>
  duration: <seconds: 4>
  type: REFINED
>
recipe: <
  result: <item: "Processor" quantity: 1>
  input: <item: "Circuit board" quantity: 2>
  input: <item: "Microcrystalline component" quantity: 2>
  duration: <seconds: 3>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Circuit board" quantity: 2>
  input: <item: "Iron ingot" quantity: 2>
  input: <item: "Copper ingot" quantity: 1>
  duration: <seconds: 1>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Microcrystalline component" quantity: 1>
  input: <item: "High-purity silicon" quantity: 2>
  input: <item: "Copper ingot" quantity: 1>
  duration: <seconds: 2>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Plastic" quantity: 1>
  input: <item: "Refined oil" quantity: 2>
  input: <item: "Energetic graphite" quantity: 1>
  duration: <seconds: 3>
  type: CHEMICAL
>

# Science
recipe: <
  result: <item: "Structure matrix" quantity: 1>
  input: <item: "Diamond" quantity: 1>
  input: <item: "Titanium crystal" quantity: 1>
  duration: <seconds: 8>
  type: RESEARCHED
>
recipe: <
  result: <item: "Energy matrix" quantity: 1>
  input: <item: "Energetic graphite" quantity: 2>
  input: <item: "Hydrogen" quantity: 2>
  duration: <seconds: 6>
  type: RESEARCHED
>
recipe: <
  result: <item: "Electromagnetic matrix" quantity: 1>
  input: <item: "Magnetic coil" quantity: 1>
  input: <item: "Circuit board" quantity: 1>
  duration: <seconds: 3>
  type: RESEARCHED
>

# Warp travel
recipe: <
  result: <item: "Space warper" quantity: 1>
  input: <item: "Graviton lens" quantity: 1>
  duration: <seconds: 10>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Graviton lens" quantity: 1>
  input: <item: "Diamond" quantity: 4>
  input: <item: "Strange matter" quantity: 1>
  duration: <seconds: 6>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Strange matter" quantity: 1>
  input: <item: "Particle container" quantity: 2>
  input: <item: "Iron ingot" quantity: 2>
  input: <item: "Deuterium" quantity: 10>
  duration: <seconds: 8>
  type: COLLIDED
>
recipe: <
  # TODO name
  result: <item: "Deuterium" quantity: 5>
  input: <item: "Hydrogen" quantity: 10>
  duration: <seconds: 5>
  type: COLLIDED
>
recipe: <
  result: <item: "Particle container" quantity: 1>
  input: <item: "Electromagnetic turbine" quantity: 2>
  input: <item: "Copper ingot" quantity: 2>
  input: <item: "Graphene" quantity: 2>
  duration: <seconds: 4>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Electromagnetic turbine" quantity: 1>
  input: <item: "Electric motor" quantity: 2>
  input: <item: "Magnetic coil" quantity: 2>
  duration: <seconds: 2>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Electric motor" quantity: 1>
  input: <item: "Iron ingot" quantity: 2>
  input: <item: "Gear" quantity: 1>
  input: <item: "Magnetic coil" quantity: 1>
  duration: <seconds: 2>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Magnetic coil" quantity: 2>
  input: <item: "Magnet" quantity: 2>
  input: <item: "Copper ingot" quantity: 1>
  duration: <seconds: 1>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Gear" quantity: 1>
  input: <item: "Iron ingot" quantity: 1>
  duration: <seconds: 1>
  type: ASSEMBLED
>

# Dyson
recipe: <
  result: <item: "Small carrier rocket" quantity: 1>
  input: <item: "Dyson sphere component" quantity: 2>
  input: <item: "Deuteron fuel rod" quantity: 2>
  input: <item: "Quantum chip" quantity: 2>
  duration: <seconds: 6>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Dyson sphere component" quantity: 1>
  input: <item: "Frame material" quantity: 3>
  input: <item: "Solar sail" quantity: 3>
  input: <item: "Processor" quantity: 3>
  duration: <seconds: 8>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Frame material" quantity: 1>
  input: <item: "Carbon nanotube" quantity: 4>
  input: <item: "Titanium alloy" quantity: 1>
  input: <item: "High-purity silicon" quantity: 1>
  duration: <seconds: 6>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Solar sail" quantity: 2>
  input: <item: "Graphene" quantity: 1>
  input: <item: "Photon combiner" quantity: 1>
  duration: <seconds: 4>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Deuteron fuel rod" quantity: 1>
  input: <item: "Titanium alloy" quantity: 1>
  input: <item: "Deuterium" quantity: 10>
  input: <item: "Super-magnetic ring" quantity: 1>
  duration: <seconds: 6>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Super-magnetic ring" quantity: 1>
  input: <item: "Electromagnetic turbine" quantity: 2>
  input: <item: "Magnet" quantity: 3>
  input: <item: "Energetic graphite" quantity: 1>
  duration: <seconds: 3>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Photon combiner" quantity: 1>
  input: <item: "Prism" quantity: 2>
  input: <item: "Circuit board" quantity: 1>
  duration: <seconds: 3>
  type: ASSEMBLED
>
recipe: <
  result: <item: "Prism" quantity: 2>
  input: <item: "Glass" quantity: 3>
  duration: <seconds: 2>
  type: ASSEMBLED
>


# Fuels
fuel: <
  item: "Coal ore"
  joules: 2700000
  type: BURNED
>
fuel: <
  item: "Energetic graphite"
  joules: 6300000
  type: BURNED
>
fuel: <
  item: "Hydrogen"
  joules: 8000000
  type: BURNED
>
fuel: <
  item: "Crude oil"
  joules: 4000000
  type: BURNED
>
fuel: <
  item: "Refined oil"
  joules: 4400000
  type: BURNED
>
fuel: <
  item: "Hydrogen fuel rod"
  joules: 40000000
  type: BURNED
>
fuel: <
  item: "Organic crystal"
  joules: 1800000
  type: BURNED
>
fuel: <
  item: "Fire ice"
  joules: 4800000
  type: BURNED
>
fuel: <
  item: "Graphene"
  joules: 96000
  type: BURNED
>

# Buildings
building: <
  name: "Mining machine"
  efficiency: 1
  active_watts_used: 420000
  idle_watts_used: 24000
  type: VEIN_HARVESTED
>
building: <
  name: "Oil extractor"
  efficiency: 1
  active_watts_used: 840000
  idle_watts_used: 24000
  type: OIL_HARVESTED
>
building: <
  name: "Water pump"
  efficiency: 1
  active_watts_used: 300000
  idle_watts_used: 12000
  type: LIQUID_HARVESTED
>
building: <
  name: "Smelter"
  efficiency: 1
  active_watts_used: 360000
  idle_watts_used: 12000
  type: SMELTED
>
building: <
  name: "Assembling machine Mk.I"
  efficiency: 0.75
  active_watts_used: 270000
  idle_watts_used: 12000
  type: ASSEMBLED
>
building: <
  name: "Assembling machine Mk.II"
  efficiency: 1
  active_watts_used: 480000
  idle_watts_used: 15000
  type: ASSEMBLED
>
building: <
  name: "Assembling machine Mk.III"
  efficiency: 1.5
  active_watts_used: 780000
  idle_watts_used: 18000
  type: ASSEMBLED
>
building: <
  name: "Oil refinery"
  efficiency: 1
  active_watts_used: 960000
  idle_watts_used: 24000
  type: REFINED
>
building: <
  name: "Chemical plant"
  efficiency: 1
  active_watts_used: 720000
  idle_watts_used: 24000
  type: CHEMICAL
>
building: <
  name: "Matrix lab"
  efficiency: 1
  active_watts_used: 480000
  idle_watts_used: 12000
  # TODO: Differentiate matrix production from research, since they have
  # different bonuses/rates
  type: RESEARCHED
>
building: <
  name: "Miniature particle collider"
  efficiency: 1
  active_watts_used: 12000000
  idle_watts_used: 120000
  type: COLLIDED
>

# Power generation
building: <
  name: "Thermal power station"
  active_watts_used: -2160000
  efficiency: 0.8
  type: BURNED
>

# Upgrades/Modifiers
# TODO: these shouldn't be static/in this config
efficiency: <
  type: VEIN_HARVESTED
  type: LIQUID_HARVESTED
  type: OIL_HARVESTED
  multiplier: 1.5
>
