// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package configpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductionType int32

const (
	ProductionType_ProductionType_UNKNOWN ProductionType = 0
	ProductionType_VEIN_HARVESTED         ProductionType = 1
	ProductionType_LIQUID_HARVESTED       ProductionType = 2
	ProductionType_OIL_HARVESTED          ProductionType = 3
	ProductionType_SMELTED                ProductionType = 4
	ProductionType_ASSEMBLED              ProductionType = 5
	ProductionType_REFINED                ProductionType = 6
	ProductionType_CHEMICAL               ProductionType = 7
	ProductionType_RESEARCHED             ProductionType = 8
	ProductionType_COLLIDED               ProductionType = 9
	ProductionType_BURNED                 ProductionType = 10
	ProductionType_NUCLEAR                ProductionType = 11
)

var ProductionType_name = map[int32]string{
	0:  "ProductionType_UNKNOWN",
	1:  "VEIN_HARVESTED",
	2:  "LIQUID_HARVESTED",
	3:  "OIL_HARVESTED",
	4:  "SMELTED",
	5:  "ASSEMBLED",
	6:  "REFINED",
	7:  "CHEMICAL",
	8:  "RESEARCHED",
	9:  "COLLIDED",
	10: "BURNED",
	11: "NUCLEAR",
}

var ProductionType_value = map[string]int32{
	"ProductionType_UNKNOWN": 0,
	"VEIN_HARVESTED":         1,
	"LIQUID_HARVESTED":       2,
	"OIL_HARVESTED":          3,
	"SMELTED":                4,
	"ASSEMBLED":              5,
	"REFINED":                6,
	"CHEMICAL":               7,
	"RESEARCHED":             8,
	"COLLIDED":               9,
	"BURNED":                 10,
	"NUCLEAR":                11,
}

func (x ProductionType) String() string {
	return proto.EnumName(ProductionType_name, int32(x))
}

func (ProductionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

type Recipe struct {
	Name   string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Result []*ItemQuantity `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	Input  []*ItemQuantity `protobuf:"bytes,3,rep,name=input,proto3" json:"input,omitempty"`
	// Types that are valid to be assigned to Timing:
	//	*Recipe_Duration
	//	*Recipe_PerMinute
	//	*Recipe_PerSecond
	Timing               isRecipe_Timing `protobuf_oneof:"timing"`
	Type                 ProductionType  `protobuf:"varint,7,opt,name=type,proto3,enum=factorysolver.ProductionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (m *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(m, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe) GetResult() []*ItemQuantity {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Recipe) GetInput() []*ItemQuantity {
	if m != nil {
		return m.Input
	}
	return nil
}

type isRecipe_Timing interface {
	isRecipe_Timing()
}

type Recipe_Duration struct {
	Duration *Duration `protobuf:"bytes,4,opt,name=duration,proto3,oneof"`
}

type Recipe_PerMinute struct {
	PerMinute float64 `protobuf:"fixed64,5,opt,name=per_minute,json=perMinute,proto3,oneof"`
}

type Recipe_PerSecond struct {
	PerSecond float64 `protobuf:"fixed64,6,opt,name=per_second,json=perSecond,proto3,oneof"`
}

func (*Recipe_Duration) isRecipe_Timing() {}

func (*Recipe_PerMinute) isRecipe_Timing() {}

func (*Recipe_PerSecond) isRecipe_Timing() {}

func (m *Recipe) GetTiming() isRecipe_Timing {
	if m != nil {
		return m.Timing
	}
	return nil
}

func (m *Recipe) GetDuration() *Duration {
	if x, ok := m.GetTiming().(*Recipe_Duration); ok {
		return x.Duration
	}
	return nil
}

func (m *Recipe) GetPerMinute() float64 {
	if x, ok := m.GetTiming().(*Recipe_PerMinute); ok {
		return x.PerMinute
	}
	return 0
}

func (m *Recipe) GetPerSecond() float64 {
	if x, ok := m.GetTiming().(*Recipe_PerSecond); ok {
		return x.PerSecond
	}
	return 0
}

func (m *Recipe) GetType() ProductionType {
	if m != nil {
		return m.Type
	}
	return ProductionType_ProductionType_UNKNOWN
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Recipe) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Recipe_Duration)(nil),
		(*Recipe_PerMinute)(nil),
		(*Recipe_PerSecond)(nil),
	}
}

type ItemQuantity struct {
	Item                 string   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemQuantity) Reset()         { *m = ItemQuantity{} }
func (m *ItemQuantity) String() string { return proto.CompactTextString(m) }
func (*ItemQuantity) ProtoMessage()    {}
func (*ItemQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *ItemQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemQuantity.Unmarshal(m, b)
}
func (m *ItemQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemQuantity.Marshal(b, m, deterministic)
}
func (m *ItemQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemQuantity.Merge(m, src)
}
func (m *ItemQuantity) XXX_Size() int {
	return xxx_messageInfo_ItemQuantity.Size(m)
}
func (m *ItemQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_ItemQuantity proto.InternalMessageInfo

func (m *ItemQuantity) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ItemQuantity) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Fuel struct {
	Item                 string         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Joules               int64          `protobuf:"varint,2,opt,name=joules,proto3" json:"joules,omitempty"`
	Type                 ProductionType `protobuf:"varint,5,opt,name=type,proto3,enum=factorysolver.ProductionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Fuel) Reset()         { *m = Fuel{} }
func (m *Fuel) String() string { return proto.CompactTextString(m) }
func (*Fuel) ProtoMessage()    {}
func (*Fuel) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *Fuel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fuel.Unmarshal(m, b)
}
func (m *Fuel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fuel.Marshal(b, m, deterministic)
}
func (m *Fuel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fuel.Merge(m, src)
}
func (m *Fuel) XXX_Size() int {
	return xxx_messageInfo_Fuel.Size(m)
}
func (m *Fuel) XXX_DiscardUnknown() {
	xxx_messageInfo_Fuel.DiscardUnknown(m)
}

var xxx_messageInfo_Fuel proto.InternalMessageInfo

func (m *Fuel) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *Fuel) GetJoules() int64 {
	if m != nil {
		return m.Joules
	}
	return 0
}

func (m *Fuel) GetType() ProductionType {
	if m != nil {
		return m.Type
	}
	return ProductionType_ProductionType_UNKNOWN
}

type Building struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActiveWattsUsed      int64          `protobuf:"varint,2,opt,name=active_watts_used,json=activeWattsUsed,proto3" json:"active_watts_used,omitempty"`
	IdleWattsUsed        int64          `protobuf:"varint,3,opt,name=idle_watts_used,json=idleWattsUsed,proto3" json:"idle_watts_used,omitempty"`
	Efficiency           float64        `protobuf:"fixed64,4,opt,name=efficiency,proto3" json:"efficiency,omitempty"`
	Type                 ProductionType `protobuf:"varint,5,opt,name=type,proto3,enum=factorysolver.ProductionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Building) Reset()         { *m = Building{} }
func (m *Building) String() string { return proto.CompactTextString(m) }
func (*Building) ProtoMessage()    {}
func (*Building) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *Building) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Building.Unmarshal(m, b)
}
func (m *Building) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Building.Marshal(b, m, deterministic)
}
func (m *Building) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Building.Merge(m, src)
}
func (m *Building) XXX_Size() int {
	return xxx_messageInfo_Building.Size(m)
}
func (m *Building) XXX_DiscardUnknown() {
	xxx_messageInfo_Building.DiscardUnknown(m)
}

var xxx_messageInfo_Building proto.InternalMessageInfo

func (m *Building) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Building) GetActiveWattsUsed() int64 {
	if m != nil {
		return m.ActiveWattsUsed
	}
	return 0
}

func (m *Building) GetIdleWattsUsed() int64 {
	if m != nil {
		return m.IdleWattsUsed
	}
	return 0
}

func (m *Building) GetEfficiency() float64 {
	if m != nil {
		return m.Efficiency
	}
	return 0
}

func (m *Building) GetType() ProductionType {
	if m != nil {
		return m.Type
	}
	return ProductionType_ProductionType_UNKNOWN
}

type Bonus struct {
	Type                 []ProductionType `protobuf:"varint,1,rep,packed,name=type,proto3,enum=factorysolver.ProductionType" json:"type,omitempty"`
	Multiplier           float64          `protobuf:"fixed64,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Bonus) Reset()         { *m = Bonus{} }
func (m *Bonus) String() string { return proto.CompactTextString(m) }
func (*Bonus) ProtoMessage()    {}
func (*Bonus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *Bonus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bonus.Unmarshal(m, b)
}
func (m *Bonus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bonus.Marshal(b, m, deterministic)
}
func (m *Bonus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bonus.Merge(m, src)
}
func (m *Bonus) XXX_Size() int {
	return xxx_messageInfo_Bonus.Size(m)
}
func (m *Bonus) XXX_DiscardUnknown() {
	xxx_messageInfo_Bonus.DiscardUnknown(m)
}

var xxx_messageInfo_Bonus proto.InternalMessageInfo

func (m *Bonus) GetType() []ProductionType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Bonus) GetMultiplier() float64 {
	if m != nil {
		return m.Multiplier
	}
	return 0
}

type Config struct {
	Recipe               []*Recipe   `protobuf:"bytes,1,rep,name=recipe,proto3" json:"recipe,omitempty"`
	Fuel                 []*Fuel     `protobuf:"bytes,2,rep,name=fuel,proto3" json:"fuel,omitempty"`
	Building             []*Building `protobuf:"bytes,3,rep,name=building,proto3" json:"building,omitempty"`
	Efficiency           []*Bonus    `protobuf:"bytes,4,rep,name=efficiency,proto3" json:"efficiency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetRecipe() []*Recipe {
	if m != nil {
		return m.Recipe
	}
	return nil
}

func (m *Config) GetFuel() []*Fuel {
	if m != nil {
		return m.Fuel
	}
	return nil
}

func (m *Config) GetBuilding() []*Building {
	if m != nil {
		return m.Building
	}
	return nil
}

func (m *Config) GetEfficiency() []*Bonus {
	if m != nil {
		return m.Efficiency
	}
	return nil
}

type Duration struct {
	Seconds              int32    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Millis               int32    `protobuf:"varint,2,opt,name=millis,proto3" json:"millis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{6}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Duration) GetMillis() int32 {
	if m != nil {
		return m.Millis
	}
	return 0
}

func init() {
	proto.RegisterEnum("factorysolver.ProductionType", ProductionType_name, ProductionType_value)
	proto.RegisterType((*Recipe)(nil), "factorysolver.Recipe")
	proto.RegisterType((*ItemQuantity)(nil), "factorysolver.ItemQuantity")
	proto.RegisterType((*Fuel)(nil), "factorysolver.Fuel")
	proto.RegisterType((*Building)(nil), "factorysolver.Building")
	proto.RegisterType((*Bonus)(nil), "factorysolver.Bonus")
	proto.RegisterType((*Config)(nil), "factorysolver.Config")
	proto.RegisterType((*Duration)(nil), "factorysolver.Duration")
}

func init() {
	proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4)
}

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x8d, 0xf9, 0x30, 0x66, 0x08, 0xc4, 0xd9, 0xa6, 0xa9, 0x95, 0xaa, 0x2d, 0xe2, 0xd0, 0xa2,
	0x48, 0x21, 0x0a, 0x69, 0x6f, 0x55, 0x25, 0xc0, 0x8e, 0xb0, 0x6a, 0x48, 0xb3, 0x84, 0x44, 0xca,
	0x05, 0x81, 0x59, 0xe8, 0x56, 0xfe, 0xaa, 0xbd, 0x4e, 0xc5, 0x5f, 0xeb, 0xbd, 0xa7, 0xfe, 0x80,
	0xfe, 0x9d, 0x6a, 0x17, 0x43, 0xc0, 0x8a, 0xd4, 0xa8, 0xb7, 0x9d, 0x37, 0xef, 0xed, 0xc7, 0x9b,
	0x99, 0x85, 0x5d, 0xdb, 0xf7, 0x66, 0x74, 0xde, 0x08, 0x42, 0x9f, 0xf9, 0xa8, 0x3c, 0x1b, 0xdb,
	0xcc, 0x0f, 0x17, 0x91, 0xef, 0xdc, 0x93, 0xb0, 0xf6, 0x33, 0x03, 0x32, 0x26, 0x36, 0x0d, 0x08,
	0x42, 0x90, 0xf3, 0xc6, 0x2e, 0xd1, 0xa4, 0xaa, 0x54, 0x2f, 0x62, 0xb1, 0x46, 0xe7, 0x20, 0x87,
	0x24, 0x8a, 0x1d, 0xa6, 0x65, 0xaa, 0xd9, 0x7a, 0xa9, 0xf9, 0xb2, 0xb1, 0x25, 0x6f, 0x98, 0x8c,
	0xb8, 0x57, 0xf1, 0xd8, 0x63, 0x94, 0x2d, 0x70, 0x42, 0x45, 0x67, 0x90, 0xa7, 0x5e, 0x10, 0x33,
	0x2d, 0xfb, 0x6f, 0xcd, 0x92, 0x89, 0x3e, 0x80, 0x32, 0x8d, 0xc3, 0x31, 0xa3, 0xbe, 0xa7, 0xe5,
	0xaa, 0x52, 0xbd, 0xd4, 0x7c, 0x91, 0x52, 0xe9, 0x49, 0xba, 0xbb, 0x83, 0xd7, 0x54, 0xf4, 0x06,
	0x20, 0x20, 0xe1, 0xc8, 0xa5, 0x5e, 0xcc, 0x88, 0x96, 0xaf, 0x4a, 0x75, 0xa9, 0xbb, 0x83, 0x8b,
	0x01, 0x09, 0x7b, 0x02, 0x5a, 0x11, 0x22, 0x62, 0xfb, 0xde, 0x54, 0x93, 0x37, 0x08, 0x03, 0x01,
	0xa1, 0x33, 0xc8, 0xb1, 0x45, 0x40, 0xb4, 0x42, 0x55, 0xaa, 0x57, 0x9a, 0xaf, 0x52, 0x87, 0x7e,
	0x09, 0xfd, 0x69, 0x6c, 0xf3, 0xa3, 0xae, 0x17, 0x01, 0xc1, 0x82, 0xda, 0x56, 0x40, 0x66, 0xd4,
	0xa5, 0xde, 0xbc, 0xf6, 0x09, 0x76, 0x37, 0x1f, 0xc3, 0x1d, 0xa4, 0x8c, 0xb8, 0x2b, 0x07, 0xf9,
	0x1a, 0x1d, 0x81, 0xf2, 0x3d, 0xc9, 0x6b, 0x99, 0xaa, 0x54, 0xcf, 0xe3, 0x75, 0x5c, 0x23, 0x90,
	0xbb, 0x88, 0x89, 0xf3, 0xa8, 0xee, 0x10, 0xe4, 0x6f, 0x7e, 0xec, 0x90, 0x48, 0xa8, 0xb2, 0x38,
	0x89, 0xd6, 0x17, 0xce, 0x3f, 0xf9, 0xc2, 0xb5, 0x5f, 0x12, 0x28, 0xed, 0x98, 0x3a, 0x53, 0xea,
	0xcd, 0x1f, 0xad, 0xf2, 0x31, 0xec, 0x8f, 0x6d, 0x46, 0xef, 0xc9, 0xe8, 0xc7, 0x98, 0xb1, 0x68,
	0x14, 0x47, 0x64, 0x9a, 0x1c, 0xbb, 0xb7, 0x4c, 0xdc, 0x72, 0x7c, 0x18, 0x91, 0x29, 0x7a, 0x0b,
	0x7b, 0x74, 0xea, 0x6c, 0x31, 0xb3, 0x82, 0x59, 0xe6, 0xf0, 0x03, 0xef, 0x35, 0x00, 0x99, 0xcd,
	0xa8, 0x4d, 0x89, 0x67, 0x2f, 0x44, 0x4d, 0x25, 0xbc, 0x81, 0xfc, 0xcf, 0x3b, 0xee, 0x20, 0xdf,
	0xf6, 0xbd, 0xf8, 0xc1, 0x03, 0xa9, 0x9a, 0x7d, 0xa2, 0x96, 0x5f, 0xc7, 0x8d, 0x1d, 0x46, 0x03,
	0x87, 0x92, 0x50, 0xbc, 0x4d, 0xc2, 0x1b, 0x48, 0xed, 0xb7, 0x04, 0x72, 0x47, 0xcc, 0x09, 0x3a,
	0xe1, 0x3d, 0xcf, 0x27, 0x42, 0xec, 0x5f, 0x6a, 0x3e, 0x4f, 0xed, 0xbf, 0x1c, 0x17, 0x9c, 0x90,
	0xd0, 0x3b, 0xc8, 0xcd, 0x62, 0xe2, 0x24, 0x03, 0xf2, 0x2c, 0x45, 0xe6, 0xf5, 0xc5, 0x82, 0x80,
	0xce, 0x41, 0x99, 0x24, 0x55, 0x48, 0x26, 0x23, 0xdd, 0xe3, 0xab, 0x22, 0xe1, 0x35, 0x11, 0xbd,
	0x4f, 0xd9, 0xc8, 0x65, 0x07, 0x69, 0x19, 0x37, 0x65, 0xd3, 0xdc, 0xda, 0x47, 0x50, 0x56, 0xf3,
	0x82, 0x34, 0x28, 0x2c, 0xdb, 0x3f, 0x12, 0x35, 0xcf, 0xe3, 0x55, 0xc8, 0x5b, 0xcc, 0xa5, 0x8e,
	0x43, 0xa3, 0xa4, 0x31, 0x93, 0xe8, 0xf8, 0x8f, 0x04, 0x95, 0x6d, 0x13, 0xd1, 0x11, 0x1c, 0x6e,
	0x23, 0xa3, 0x61, 0xff, 0x73, 0xff, 0xf2, 0xb6, 0xaf, 0xee, 0x20, 0x04, 0x95, 0x1b, 0xc3, 0xec,
	0x8f, 0xba, 0x2d, 0x7c, 0x63, 0x0c, 0xae, 0x0d, 0x5d, 0x95, 0xd0, 0x01, 0xa8, 0x96, 0x79, 0x35,
	0x34, 0xf5, 0x0d, 0x34, 0x83, 0xf6, 0xa1, 0x7c, 0x69, 0x5a, 0x1b, 0x50, 0x16, 0x95, 0xa0, 0x30,
	0xe8, 0x19, 0x16, 0x0f, 0x72, 0xa8, 0x0c, 0xc5, 0xd6, 0x60, 0x60, 0xf4, 0xda, 0x96, 0xa1, 0xab,
	0x79, 0x9e, 0xc3, 0xc6, 0x85, 0xd9, 0x37, 0x74, 0x55, 0x46, 0xbb, 0xa0, 0x74, 0xba, 0x46, 0xcf,
	0xec, 0xb4, 0x2c, 0xb5, 0x80, 0x2a, 0x00, 0xd8, 0x18, 0x18, 0x2d, 0xdc, 0xe9, 0x1a, 0xba, 0xaa,
	0x88, 0xec, 0xa5, 0x65, 0x99, 0xba, 0xa1, 0xab, 0x45, 0x04, 0x20, 0xb7, 0x87, 0x98, 0xeb, 0x80,
	0x6f, 0xd2, 0x1f, 0x76, 0x2c, 0xa3, 0x85, 0xd5, 0x52, 0xfb, 0xf8, 0xae, 0x3e, 0xa7, 0xec, 0x6b,
	0x3c, 0x69, 0xd8, 0xbe, 0x7b, 0x3a, 0x19, 0x07, 0x2c, 0x3c, 0x4d, 0xbc, 0x3c, 0x59, 0x9a, 0x79,
	0xba, 0xfc, 0x2c, 0x83, 0xc9, 0x44, 0x16, 0xff, 0xe5, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0x53, 0x80, 0x13, 0x3f, 0x05, 0x00, 0x00,
}
